### PR TITLE
fixed broken links

### PR DESCRIPTION
**Pull request by buhlerax**
Broken Link removed.
Link with wrong syntax were fixed.

### CODE REVIEW

**Comment by auroraeosrose** [comment]
Instead of commenting these out, could you just delete them please?

**Comment by buhlerax** [comment]
aurora did right now?

**Comment by buhlerax** [comment]
Auroraeosrose,
I did a few more commits to the index.php and downloads
and sent the push.
Thank you.

**Comment by buhlerax** [comment]
Auroraeosrose,
Good day,
You can do the merge?
Thank you.

**Comment by buhlerax** [comment]
The change were not published. I lost the will to participate.

**Pull request closed without merging**
