### PR TITLE
fix a error in php-gtk history

### PR DESCRIPTION
**Pull request by marcosptf**
before => TKG
after => GTK

### CODE REVIEW

**Comment by buhlerax** [comment]
Marcos,
Good day,
I will merge in git.php.net.
Because I do not have access at github.
But I will give due credit to you in the comments.
Thank you for your participation.
______________________________________
Marcos,
Bom dia,
Eu farei o merge pelo git.php.net.
Pois eu não tenho acesso pelo github.
Mas darei os devidos créditos para você nos comentários.
Obrigado pela sua participação.

**Comment by Tyrael** [comment]
@buhlerax you can still merge those commits manually(without github access to the php project) to your git.php.net clone via https://gist.github.com/Tyrael/259f0f8a24c9c1a5816b
that way the commits were also preserve the author information which is better than having them in comments.

**Comment by buhlerax** [comment]
Tyrael,
Good day,
I'll try to do the merge as described by you.
thank you

**Comment by Tyrael** [comment]
let me know if you need further assistance, you can also poke me on irc (Tyrael on efnet)

**Comment by buhlerax** [comment]
Hi,
Good afternoon,
Merge done in correction in the translation into English by marcosptf.
Thank You marcosptf and sorry for the delay.
Credit for his corrections have been preserved: http://git.php.net/?p=web/gtk.git;a=summary with the help of Tyrael.

**Comment by marcosptf** [comment]
@buhlerax @Tyrael 
I would like thank you the opportunity to help this great project!!!

Have a nice week!
@phpsp 
:-)

**Pull request merged**
